### PR TITLE
Add new website to Beginner section

### PR DESCRIPTION
**Pull request by sjtushi**
Add new Resource LabEx for the Beginner Section. 

The existing list isn’t alphabetically sorted, so I'm unsure where to add it. Please let me know if I’ve made any mistakes.

Thanks for creating this helpful list!

### CODE REVIEW

**Comment by karlhorky** [comment]
@sjtushi I'm glad that the list is helpful!

Thanks for this PR. Looking at [the Product Hunt launch](https://www.producthunt.com/products/labex-beta), [the YouTube video](https://www.youtube.com/watch?v=ZMH_HfbS-wY) and [the GitHub profile](https://github.com/labex-labs), I would categorize this more under the "Linux, Docker, DevOps, Python" topics that they listed (the other topics can also be listed) and because of this, I would move it into the Intermediate section above PluralSight

**Comment by karlhorky** [comment]
I applied the change, thanks for the contribution!

**Comment by karlhorky** [comment]
@sjtushi I guess you are maybe working for LabEx? I noticed your contributions such as:

- https://github.com/labex-labs/support/pull/2

**Comment by sjtushi** [comment]
@karlhorky  Thank you for updating and merging so quickly. Yes, I work at LabEx.

**Pull request merged**
