### PR TITLE
Added my blog (read description)

### PR DESCRIPTION
**Pull request by Booligoosh**
Note that yes, I am promoting my blog but at the moment I don't make any money off it and the reason that I want more people to visit it isn't to shove ads into their faces but I genuinely want to help more people.

### CODE REVIEW

**Comment by karlhorky** [comment]
Hi @Booligoosh, thanks for your contribution. Unfortunately this won't make the list, for these reasons:

- the blog format is not what I'm looking for
- it's a bit too self-promotional for my tastes (email list, facebook page links, etc)
- the content of the [learn page](https://codetheweb.blog/learn) does not go deep enough and is not an optimal way to learn in my opinion

Good luck on your blog! I'd be happy to review it again if there was significant changes to these points.

**Comment by Booligoosh** [comment]
Hey @karlhorky , that's fine - I really appreciate your feedback, it is way better than people who just ignore you. Out of interest is the reason that the learn page is not deep enough because it just has links or are you saying that there is not enough / not the right content

**Comment by karlhorky** [comment]
Not enough content, and the presentation of said content could be better too (maybe show the results more often or offer interactive code editors embedded in the page?).

**Comment by Booligoosh** [comment]
@karlhorky Ok thanks for the feedback, I will work on it! 😻

**Comment by karlhorky** [comment]
No problem, glad to help!

**Pull request closed without merging**
